name: Are They Asleep

on:
  pull_request:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
  issues:
    types: -opened
    
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check if teammate is awake?
        id: are-they-asleep
        uses: shundor/are-they-asleep@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}         
