name: Are They Awake Yet
on: [pull_request, issues]

jobs:
  are-they-awake-yet:
    runs-on: ubuntu-latest
    steps:
      - name: are-they-awake-yet
        uses: benhayehudi/awake-yet-action@master
        with:
          entryPoint: GITHUB_TOKEN
          args: GOOGLE_API_KEY
    env:
      GITHUB_TOKEN: '${{ secrets.SECRET_TOKEN}}'
      GOOGLE_API_KEY: '${{ secrets.GOOGLE_API_KEY }}'
