name: Are They Awake Yet
on: 
  pull_request:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
  issues:
    types:
      -opened

jobs:
  are-they-awake-yet:
    runs-on: ubuntu-latest
    steps:
      - name: are-they-awake-yet
        uses: JulieGunawan/awake-yet-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN}}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
