name: Are They Awake Yet
on: 
  pull_request:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
  issues:
    types:
      -opened

jobs:
  are-they-awake-yet:
    runs-on: ubuntu-latest
    steps:
       - name: "dump github context"
         run: echo '${{ toJSON(github.event) }}' | jq
         shell: bash
       - name: Checkout Code
         uses: actions/checkout@v2
       - name: are-they-awake-yet
         uses: JulieGunawan/awake-yet-action@master
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN}}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
