name: Create Calendar Event

on:
  pull_request:
    branches: 
      - main

jobs:
  create-event:
    runs-on: ubuntu-latest
    name: Create Event using Ms. Graph
    steps:
      - name: Print a message
        run: echo calling a Github Action

      - name: Message dump
        run: echo '${{ toJSON(github.event) }}' | jq
        
      - name: Create event on the next day
        uses: JulieGunawan/ms-graph-create-event-msal@main
        env:
          TENANT_NAME: ${{secrets.TENANT_NAME}}
          APP_ID: ${{secrets.APP_ID}}
          APP_SECRET: ${{secrets.APP_SECRET}}
        with:
          subject: 'Review pull request'
          body: 'A new PR has been submitted on ${{ github.repository }} from ${{ github.actor }}. Please review it.'
          emailaddress: 'h4m_h4m17@yahoo.com'
