name: Create Calendar Event

on:
  pull_request:
    branches: 
      - main

jobs:   
  create-event:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    name: Create Event using Ms. Graph
    steps:
      - name: Print a message
        run: echo About to call a Github Action

      - name: Message dump
        run: echo '${{ toJSON(github.event) }}' | jq
        
      - name: Create event on the next day
        uses: JulieGunawan/ms-graph-create-event-msal@main      
        with:
          clientId: ${{secrets.CLIENT_ID}}
          clientSecret: ${{secrets.CLIENT_SECRET}}
          tenantId: ${{secrets.TENANT_ID}}
          subject: 'Review pull request'
          body: 'A new PR has been submitted on ${{ github.repository }} from ${{ github.actor }}. Please review it.'
          userEmail: 'h4m_h4m17@yahoo.com'
