name: Lint code

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.1

      - name: Setup node.js 16.x, 180x, 20.x
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint -- --fix
