name: ROI PR metrics

on:
  pull_request:
    types: [review_requested]

jobs:
  record_pr_timestamp:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Get Current Timestamp for PR
        id: pr_timestamp
        run: echo "::set-output name=pr_timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

  get_issue_timestamp:
    needs: record_pr_timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get Issue Timestamp
        id: get_issue_timestamp
        working-directory: roiScript
        run:
          | # timestamp: Dunridge, issue #767: 2023-11-14 16:06:02 # TODO: specify all of the conditions in this cat command for telling apart the users
          issue_timestamp=$(cat issue_timestamp.log | awk -F ': ' '{print $2}')
          echo "Issue timestamp from the first step: ${issue_timestamp}"
          echo "::set-output name=issue_timestamp::${issue_timestamp}"

  calculate_time_difference:
    needs: get_issue_timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Time Difference # TODO: debug this
        id: time_difference
        run: |
          issue_timestamp=${{ needs.get_issue_timestamp.outputs.issue_timestamp }}
          echo "Issue timestamp: ${issue_timestamp}"
          pr_timestamp=${{ needs.record_pr_timestamp.outputs.pr_timestamp }}
          echo "PR timestamp: ${pr_timestamp}"
          issue_time=$(date -d "${issue_timestamp}" +%s)
          echo "Issue time: ${issue_time}"
          pr_time=$(date -d "${pr_timestamp}" +%s)
          echo "PR time: ${pr_time}"
          time_diff=$((pr_time - issue_time))
          echo "Time Difference: ${time_diff}"
          echo "::set-output name=time_diff::${time_diff}"

  metric:
    needs: calculate_time_difference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # pick the node version that's compatible with libraries

      - name: Print Node.js path
        run: which node

      - name: Install
        run: npm install
        working-directory: ./roiScript

      #  PR_PAYLOAD: ${{ steps.pr-payload.outputs.pr_payload }}
      - name: Run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIME_DIFF: ${{ needs.calculate_time_difference.outputs.time_diff }}
        run: node ./roiScript/issue-metrics.mjs
